## Embedding of the data


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
##sentence example
sentence=[
    "the glass of milk",
    "the glass o juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understands the meaning of the word"
]

In [17]:
## define the vocabulary size
voc_size=10000

In [6]:
## one hot representation
one_hot_representation=[one_hot(words,voc_size) for words in sentence]

In [7]:
one_hot_representation

[[857, 446, 407, 550],
 [857, 446, 163, 608],
 [857, 225, 407, 674],
 [834, 601, 220, 802, 469],
 [834, 601, 220, 802, 790],
 [978, 857, 681, 407, 857, 199]]

In [24]:
## word embedding representation
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
max_sentence_length=8
embedded_docs=pad_sequences(one_hot_representation,padding="pre",maxlen=max_sentence_length)


In [12]:
print(embedded_docs)

[[  0   0   0   0 857 446 407 550]
 [  0   0   0   0 857 446 163 608]
 [  0   0   0   0 857 225 407 674]
 [  0   0   0 834 601 220 802 469]
 [  0   0   0 834 601 220 802 790]
 [  0   0 978 857 681 407 857 199]]


In [13]:
## feature representation
dim=10

In [25]:
model=Sequential()
model.add(Input(shape=(max_sentence_length,)))
model.add(Embedding(voc_size,dim))
model.compile(optimizer="adam",loss="mse")

In [26]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[-0.00246789, -0.00560158, -0.02820126,  0.01579771,  0.01546438,
        -0.02847409,  0.03680151,  0.00942468, -0.03485775, -0.04780208],
       [-0.00246789, -0.00560158, -0.02820126,  0.01579771,  0.01546438,
        -0.02847409,  0.03680151,  0.00942468, -0.03485775, -0.04780208],
       [-0.00246789, -0.00560158, -0.02820126,  0.01579771,  0.01546438,
        -0.02847409,  0.03680151,  0.00942468, -0.03485775, -0.04780208],
       [-0.00246789, -0.00560158, -0.02820126,  0.01579771,  0.01546438,
        -0.02847409,  0.03680151,  0.00942468, -0.03485775, -0.04780208],
       [ 0.04817038,  0.0002944 ,  0.01877284,  0.02316645, -0.02020706,
        -0.04329661,  0.03276941,  0.02215016, -0.02205409,  0.03843066],
       [-0.02682575,  0.02989867,  0.03540413,  0.04969795,  0.01997152,
        -0.04744637, -0.04794101,  0.04990527, -0.00463424, -0.02212644],
       [ 0.02672167,  0.02196366,  0.03747784, -0.01615393,  0.00851703,
        -0.02764748, -0.03786058,  0.03127222